(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(blink-cursor-mode nil)
 '(calendar-latitude 51.5)
 '(calendar-location-name "London")
 '(calendar-longitude -0.13)
 '(command-frequency-autosave-mode t)
 '(command-frequency-mode t)
 '(deft-auto-save-interval 5.0)
 '(deft-extension "txt")
 '(deft-text-mode (quote markdown-mode))
 '(display-time-24hr-format t)
 '(display-time-day-and-date t)
 '(display-time-default-load-average nil)
 '(display-time-hook nil)
 '(display-time-mode t)
 '(display-time-world-list (quote (("America/Los_Angeles" "Seattle") ("America/New_York" "New York") ("Europe/London" "London") ("Europe/Paris" "Paris") ("Asia/Calcutta" "Bangalore") ("Asia/Tokyo" "Tokyo") ("Australia/Perth" "Perth") ("Australia/Sydney" "Sydney"))))
 '(display-time-world-time-format "%A,%t %d %B %R %Z")
 '(exec-path (quote ("/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Applications/Emacs.app/Contents/MacOS/bin" "/usr/local/bin")))
 '(flyspell-default-dictionary "en")
 '(global-linum-mode t)
 '(haskell-notify-p t)
 '(haskell-process-type (quote ghci))
 '(haskell-stylish-on-save t)
 '(haskell-tags-on-save t)
 '(history-length 3000)
 '(hl-paren-background-colors (quote ("black" "white" "black" "white" "black" "white" "black" "white")))
 '(hl-paren-colors (quote ("blue" "black" "red" "green" "blue" "black" "red" "green")))
 '(imenu-auto-rescan t)
 '(ispell-program-name "/usr/local/bin/aspell" t)
 '(line-number-display-limit 80)
 '(markdown-command "/usr/local/bin/markdown")
 '(menu-bar-mode t)
 '(minibuffer-prompt-properties (quote (read-only t point-entered minibuffer-avoid-prompt face minibuffer-prompt)))
 '(nrepl-buffer-name-show-port t)
 '(org-agenda-file-regexp "\\`[^.].*\\.org\\'")
 '(org-agenda-files (quote ("~/.deft/")))
 '(org-log-done (quote time))
 '(recentf-exclude (quote ("\\.deft/deft-.*.org")))
 '(recentf-max-menu-items 200)
 '(recentf-max-saved-items 500)
 '(recentf-mode t)
 '(savehist-mode t)
 '(sclang-auto-scroll-post-buffer t)
 '(sclang-eval-line-forward nil)
 '(sclang-help-path (quote ("/Applications/SuperCollider/Help")))
 '(show-paren-mode t)
 '(slime-repl-history-remove-duplicates t)
 '(slime-repl-history-size 2000)
 '(slime-repl-history-trim-whitespaces t)
 '(todochiku-message-too nil)
 '(tool-bar-mode nil)
 '(word-wrap t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#042028" :foreground "#708183" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 160 :width normal :family "Inconsolata"))))
 '(diff-added ((t (:foreground "Green"))))
 '(diff-removed ((t (:foreground "Red"))))
 '(ediff-even-diff-A ((((class color) (background dark)) (:background "dark green"))))
 '(ediff-even-diff-B ((((class color) (background dark)) (:background "dark red"))))
 '(ediff-odd-diff-A ((((class color) (background dark)) (:background "dark green"))))
 '(ediff-odd-diff-B ((((class color) (background dark)) (:background "dark red"))))
 '(eval-sexp-fu-flash ((((class color) (background dark)) (:background "grey15" :foreground "DeepPink3"))))
 '(linum ((t (:height 0.8))))
 '(mumamo-background-chunk-major ((((class color) (background dark)) (:background "black"))))
 '(mumamo-background-chunk-submode1 ((((class color) (background dark)) (:background "black")))))
